M48
; DRILL file {KiCad 9.0.2} date 2025-09-14T14:53:03+0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-09-14T14:53:03+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0374
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0512
%
G90
G05
T1
X8.0994Y-1.7569
X8.4144Y-1.7569
T2
X8.2244Y-2.7331
T3
X8.2244Y-2.4381
M30
